meta_product_name: "LabelWise"
meta_title: "LabelWise - Know What You Eat, Instantly."
meta_description: "An app with nutrition label scanning that stores information about the foods you eat."
meta_image: "logo.png" # should exist in `app/assets/images/`
