meta_product_name: "LabelWise"
meta_title: "LabelWise-Know What You Eat"
meta_description: "An app allowing you to scan nutrition labels in any language for a rapid breakdown of ingredients and other key information"
meta_image: "logo.png"
